config/routes.rb
RailsMonkey::Application.routes.draw do
  root :to => 'surveys#index'
  resources :questions, :only => [:new, :create, :show]
  resources :surveys, :only => [:index, :new, :create, :show]
  resources :completions, :only => [:create]

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	attr_accessible :choice_id
	belongs_to :choice
	belongs_to :completion

	validates :choice_id, :presence => true
end

app/models/choice.rb
class Choice < ActiveRecord::Base
  attr_accessible :content
  belongs_to :question
  has_many :answers

  validates :content, :presence => true
end

app/models/completion.rb
class Completion < ActiveRecord::Base
  attr_accessible :answers_attributes, :survey_id
  has_many :answers
  belongs_to :survey
  accepts_nested_attributes_for :answers

  validates :answers, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :choices_attributes
  has_many :choices
  belongs_to :survey
  accepts_nested_attributes_for :choices

  validates :content, :presence => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :title, :description, :questions_attributes
  has_many :questions
  has_many :completions
  accepts_nested_attributes_for :questions
	
  validates :title, :presence => true
  validates :description, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
	def create
		Completion.create(params[:completion])
		redirect_to root_path
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def new
		@question = Question.new
		5.times do
			@question.choices.build
		end
	end

	def create
		@question = Question.new(params[:question])
		if @question.save
			redirect_to root_path
		else
			render :new
		end
	end

	def show
	end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def index
		@surveys = Survey.all
	end

	def new
		@survey = Survey.new
		3.times do
			@survey.questions.build
		end
		@survey.questions.each do |question|
			5.times do
				question.choices.build
			end
		end
	end

	def create
		@survey = Survey.new(params[:survey])
		if @survey.save
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		@survey = Survey.find(params[:id])
		@questions = @survey.questions
		@completion = Completion.new
		num_questions = @questions.count
		num_questions.times do
			@completion.answers.build
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMonkey</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
<%= form_for @question do |q| %>
	<%= q.label :content %>
  <%= q.text_field :content %>
  <BR>
  <% @question.choices.each do |choice| %>
  	<%= q.fields_for :choices, choice do |c| %>
  	  Choice: <%= c.text_field :content %>
  	  <BR>
  	<% end %>	
  <% end %>
  <%= q.submit %>
<% end %>

app/views/surveys/index.html.erb
<h1><span id="a">H</span><span id="b">i</span> <span id="c">S</span><span id="d">h</span><span id="e">a</span><span id="f">d</span><span id="g">y</span></h1>
<%= link_to "New Survey", new_survey_path %>
<BR>
<BR>
<ul>
<% @surveys.each do |survey| %>
	<li>
		<%= link_to survey.title, survey %>
	</li>
<% end %>
</ul>

app/views/surveys/new.html.erb
<%= form_for @survey do |s| %>
  <%= s.label :title %>
  <%= s.text_field :title %>
  <BR>
  <%= s.label :description %>
  <%= s.text_area :description %>
  <BR>
  <% @survey.questions.each do |question| %>
    <%= s.fields_for :questions, question do |q| %>
    <BR><BR>
    	<%= q.label :content %>
      <%= q.text_field :content, :class => "question" %>
      <BR>
      <% question.choices.each do |choice| %>
        <%= q.fields_for :choices, choice do |c| %>
          - Choice: <%= c.text_field :content, :class => "choice" %>
          <BR>
      	<% end %>	
      <% end %>
    <% end %>
  <% end %>
  <%= s.submit %>
<% end %>

app/views/surveys/show.html.erb
<h1><%= @survey.title %></h1>

<%= form_for @completion do |c| %> 
	<% @completion.answers.each_with_index do |answer, i| %>
		<%= c.fields_for :answers, answer do |a| %>
			<h3><%= @questions[i].content %></h3>
			<% @questions[i].choices.each do |choice| %>
		    <%= a.radio_button(:choice_id, choice.id) %> <%= choice.content %><BR>
			<% end %>
		<% end %>
	<% end %>
	<%= c.hidden_field :survey_id, :value => @survey.id %>
	<%= c.submit "Submit Survey" %>
<% end %>